CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tiki_id INTEGER,
  master_id INTEGER,
  sku TEXT,
  name TEXT,
  type TEXT,
  short_description TEXT,
  price INTEGER,
  list_price INTEGER,
  original_price INTEGER,
  is_authentic BOOLEAN,
  is_freeship_xtra BOOLEAN,
  is_hero BOOLEAN,
  is_top_brand BOOLEAN,
  return_reason TEXT,
  discount INTEGER,
  discount_rate INTEGER,
  rating_average REAL,
  review_count INTEGER,
  favourite_count INTEGER,
  has_ebook BOOLEAN,
  inventory_status TEXT,
  inventory_type TEXT,
  productset_group_name TEXT,
  data_version INTEGER,
  day_ago_created INTEGER,
  all_time_quantity_sold INTEGER,
  authors TEXT,
  current_seller TEXT,
  categories TEXT,
  specifications TEXT,
  breadcrumbs TEXT,
  is_seller_in_chat_whitelist BOOLEAN,
  is_tier_pricing_available BOOLEAN,
  is_tier_pricing_eligible BOOLEAN,
  crawl_time TEXT
);
